### ISSUE TITLE
Develope Size, Cargo and Container Class

### ISSUE THREAD

**Issue by Shinodari** [Shinodari/Load-Planner#1]
Develope only Back-End in Container Usecase

**Comment by Shinodari** [comment]
Uploaded lpdb.db for standalone database

**Comment by Hibino02** [comment]
ollo

**Comment by Shinodari** [comment]
Commit Message: **"Merge remote-tracking branch 'origin/container' into container"** 
because you stage the **db** file
Next time, you should stage **.java** only

**Comment by Hibino02** [comment]
ollo

**Comment by Hibino02** [comment]
╭∩╮( ͡⚆ ͜ʖ ͡⚆)╭∩╮

**Comment by Hibino02** [comment]
( y )
